-- Add fiscal fields required for NF-e emission
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS origem INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cfop TEXT DEFAULT '5102',
  ADD COLUMN IF NOT EXISTS cest TEXT,
  ADD COLUMN IF NOT EXISTS csosn TEXT DEFAULT '102',
  ADD COLUMN IF NOT EXISTS cst_icms TEXT DEFAULT '00',
  ADD COLUMN IF NOT EXISTS aliq_icms NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cst_pis TEXT DEFAULT '01',
  ADD COLUMN IF NOT EXISTS aliq_pis NUMERIC DEFAULT 1.65,
  ADD COLUMN IF NOT EXISTS cst_cofins TEXT DEFAULT '01',
  ADD COLUMN IF NOT EXISTS aliq_cofins NUMERIC DEFAULT 7.60,
  ADD COLUMN IF NOT EXISTS gtin_tributavel TEXT;